### ISSUE TITLE
Converted file doesn't have original audio track

### ISSUE THREAD

**Issue by my95z34** [FallingSnow/h265ize#12]
I'm not sure if this is by design, but when a file is converted, the audio gets dropped from 5.1 to stereo.  Linked is a sample file.

Original file: http://imgur.com/T0AJKkj
Output file: http://imgur.com/Hs1j0GD

Is there something I need to change, or an option I need to use, to get it to maintain the original audio?  I looked through the script and didn't see anything.

Thanks in advance, and thanks for the great script!

**Comment by FallingSnow** [comment]
Yes this is by design, it downmixes to dolby pro logic 2, you lose some quality but if your sound system supports dpl2 you get pretty good results for a large drop in bitrate. Also your output file says the audio codec is vorbis, that shouldn't be happening if your input is AC3. If you want to just copy all audio without modifying it, put
```
addAudioCodecToVar "copy"
return
```
above [L581](https://github.com/FallingSnow/h265ize/blob/master/h265ize#L581). Also remove `-6 dpl2` from [L817](https://github.com/FallingSnow/h265ize/blob/master/h265ize#L817) just to be safe.

Can you give me an output log up till when you start getting encoding progress percentages?

**Comment by my95z34** [comment]
Perfect, that worked.  I just ran a quick -p with it.  Here's the output:

http://pastebin.com/GhmupKUx

Thank you again!

**Comment by FallingSnow** [comment]
I forgot it's handbrake not ffmpeg so the log doesn't help lol. Can you run a preview again with `-v --debug` cause now the `(standard_in) 1: syntax error` has got me wondering about that too.

Happy you got it working.

**Comment by my95z34** [comment]
Lol, no worries.  Here ya go: http://pastebin.com/rdzD932X

**Comment by FallingSnow** [comment]
Btw, I think I found and fixed the source of the `(standard_in) 1: syntax error` error.

**Comment by my95z34** [comment]
I was just looking at that, lol.

Also, any chance to get an option to set audio settings? Ie whether or not
to convert it?

**Comment by FallingSnow** [comment]
Ask and you shall recieve: a5646ff

**Comment by my95z34** [comment]
You're amazing!  Thank you!
