### ISSUE TITLE
Feature / Question:

### ISSUE THREAD

**Issue by jscottdouglas** [FallingSnow/h265ize#24]
Not really the best place to ask this I guess but anyway to add to delete audio tracks that are not a certain language? for example I tend to get alot of stuff that is dual language however I'd like to remove everything but english / unknown. 

Also was wondering if you have anything that I might use to identify all the video files I have that contain unknown audio tracks.  Can't seem to find the best way to go about this.

Thanks!

**Comment by FallingSnow** [comment]
To answer the first part, it is possible to add a function to delete tracks that are not eng/unk since the script already identifies the languages. However, we'll have to wait till I have more free time in a week or two.

I would write a script for this. First loop through all the files in a directory and its subdirectories: https://stackoverflow.com/questions/4638874/how-to-loop-through-a-directory-recursively-to-find-files-with-certain-extension ([You can use the find function in h265ize to locate all video files](https://github.com/FallingSnow/h265ize/blob/master/h265ize#L355)). Then run something like `mediainfo` or `ffprobe` against each file and parse the output for `language: unknown` or something. If it finds it, just print the file name.

Here is an example of me parsing the output of ffprobe on each stream of a video file: https://github.com/FallingSnow/h265ize/blob/master/h265ize#L639-L641

**Comment by FallingSnow** [comment]
Sorry @jscottdouglas but I've decided that it would be too difficult to implement this feature so I am not going to.

**Comment by jscottdouglas** [comment]
can you implement labeling unknown tracks to a user input lang?

not as clean as your code but it gets the job done maybe you can get it into somewhere before it copies the audio/video, with plex it requires the video file to have a lang setting otherwise it considers the track to still be unknown even if single auto track is labeled.

> `#!/bin/bash
> setlang='eng'
> numStreams=$(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 "$1" | grep -o '\[STREAM\]' | wc -l | awk '{print $1}')
> numStreamsFromIndex=$(expr ${numStreams} - 1)
> for i in $(seq 0 "$numStreamsFromIndex"); do
> 	eval $(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep -E "codec_name|codec_type|bits_per_raw_sample|width|height|avg_frame_rate|channels")
> 	language=$(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep "TAG:language" | sed -n -e 's/^.*language=//p')
> 	title=$(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep "TAG:title" | sed -n -e 's/^.*title=//p')
> 	echo "Attempt: 1 Filename: $1 Stream Index: $i    Title: $title    Language: $language    Codec: $codec_type"
> 	if [ $codec_type = 'video' ] && [ -z "$language" ]; then
> 		if [ $i = '0' ]; then
> 			mkvpropedit "$1" --edit track:v1 --set language=$setlang
> 		else
> 			mkvpropedit "$1" --edit track:v$i --set language=$setlang
> 		fi
>         fi
> 	if [ $codec_type = 'audio' ] && [ -z "$language" ]; then
>                 if [ $i = '0' ]; then
>                         mkvpropedit "$1" --edit track:v1 --set language=$setlang
>                 else
>                         mkvpropedit "$1" --edit track:v$i --set language=$setlang
>                 fi
>         fi
> 	eval $(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep -E "codec_name|codec_type|bits_per_raw_sample|width|height|avg_frame_rate|channels")
> 	language=$(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep "TAG:language" | sed -n -e 's/^.*language=//p')
> 	title=$(ffprobe -loglevel quiet -show_streams -probesize 10000000 -analyzeduration 10000000 -select_streams $i "$1" | grep "TAG:title" | sed -n -e 's/^.*title=//p')
> 	echo "Attempt: 2 Filename: $1 Stream Index: $i    Title: $title    Language: $language    Codec: $codec_type"
> 
> done
> exit`
