### ISSUE TITLE
element type mismatch 1 != 0

### ISSUE THREAD

**Issue by shins5kai** [FallingSnow/h265ize#4]
Hi,

I have a message error when i encode and after the encode, the files are disappeared.
Erreur : 
[aac @ 0x7f898c0b3f00] element type mismatch 1 != 0

The video : -link removed by FallingSnow-
Screen of error : http://prntscr.com/8tmgue

The command  use to do this :   ./h265ize -n fr -q 19 -d h265 Ushio.to.Tora.S01E01.VOSTFR.1080p.WEBRip.x264-HORiZON.mkv

Thanks.
Regards.

**Comment by FallingSnow** [comment]
Unfortunately these are exceptions thrown by handbrake. h265ize has no connection to that error. Unless the encoding doesn't turn out how you expect handbrake's exceptions are pretty safe to ignore. I would assume this error is caused by the previous encoder used to create *Ushio.to.Tora.S01E01.VOSTFR.1080p.WEBRip.x264-HORiZON.mkv* did not meet the aac specification.

Anyway, I would encode about 10%, end the process, and check if the audio is ok. If it's good and you don't find any problems, I would just ignore the error.

If you do find a problem with the audio, you might not be able to use handbrake.

I'll see if I can get your video to work. I'll respond within the next day.

**Comment by shins5kai** [comment]
Thanks for your answers quick :)
I've already done many times the encode but every times the encoded files are missing : no in temporary repertories or destination final.
So if you have a idea where they can be ?
In the destination repertory (h265), the repertory is created but it is also empty. :/

**Comment by shins5kai** [comment]
more details : http://prntscr.com/8tsrl6

**Comment by FallingSnow** [comment]
This is very strange. I h265ized your video and it worked flawlessly, same command and everything. Just as a note; your should get more aggressive with your quality because you're only going to see a drop of 552MB to 487MB. Try 20 rather than 19.

What distro are you running?
Can you run `./h265ize -n fr -q 19 -d h265 -v --debug Ushio.to.Tora.S01E01.VOSTFR.1080p.WEBRip.x264-HORiZON.mkv` and paste the log?
Also while the encode is running can you give me the output of `ls -la $HOME/h265`

**Comment by shins5kai** [comment]
Strange, I think i have all dependencies ... I use this script in containers docker with debian lastest, do you thinks it could be a problem ?
I don't known why I have this error :x

**Comment by FallingSnow** [comment]
What your last error says is there is no subtitle in the handbrake encoding. Please make sure you handbrake is up to date. Can you give me the output of `HandBrakeCLI --version` as well?

**Comment by shins5kai** [comment]
I use docker and I thinks it's the cause of my issue : 
apt-get update
 apt-get install wget git bc handbrake-cli ffmpeg
 cd root
 wget https://raw.githubusercontent.com/FallingSnow/h265ize/master/h265ize
 chmod +x h265ize

./h265ize -q 20 -n fr Ushio.to.Tora.S01E01.VOSTFR.1080p.WEBRip.x264-HORiZON.mkv
[h265ize]: Finding videos... 
find: `file': No such file or directory

[h265ize]: No video files found.

**Comment by shins5kai** [comment]
Can you try to run you script inside a container ?

**Comment by FallingSnow** [comment]
Unfortunately I can't. Would you be able to temporarily give me access to one to debug your situation?
