### ISSUE TITLE
ffmpeg location different on Ubuntu-based systems

### ISSUE THREAD

**Issue by lublub** [FallingSnow/h265ize#5]
Quick fix:

Setting subtitle names...
/bin/ffmpeg: No such file or directory

$which ffmpeg
/usr/bin/ffmpeg

suggestion:
/bin/ffmpeg -> ffmpeg

(is it considered good practice to hard-code each executable? even /bin/rm?)

thanks for this great script.

**Comment by FallingSnow** [comment]
**(is it considered good practice to hard-code each executable? even /bin/rm?)**
I doubt it. I do it sometimes because I the systems I work in sometimes have modified utilities in `usr/bin/` or aliases for their commands. So I figured it wouldn't hurt if I hard coded to bin, but apparently that wasn't that case.

I'll follow your suggestion considering my situations would be more edge cases anyway.

You're welcome for the script too btw :) Thx for the report.
