### ISSUE TITLE
option "parallel" undefined

### ISSUE THREAD

**Issue by lublub** [FallingSnow/h265ize#7]
....
h265ize: line 793: [: : integer expression expected
....

this is line:
     if [ "${options[parallel]}" -eq 1 ]; then

I looked through the script, it seems that "parallel" is never defined...

**Comment by FallingSnow** [comment]
That's strange, since the variable is in quotes it shouldn't matter I think. I removed the variable definition because I thought it was unnecessary, guess I'll just add it back as 0. Thanks for bring this up. U da boss lublub. Sunday, 08 November 2015, 00:36PM -08:00 from lublub < notifications@github.com> :
