### ISSUE TITLE
some options maybe?

### ISSUE THREAD

**Issue by egorks** [FallingSnow/h265ize#76]
hi Ayrton,

i am wondering whether implicit autocropping is a good idea. of course if 16:9 was encoded as 4:3 and black stripes get detected - its very good. but in other cases i don't see a reason to lose several pixels here and there if all vids are proper aspect and cropping (which they normally are).
would it be possible to add an option to influence cropping somehow? at least turn it off and on...

an option to influence deinterlacing/detelecine would be great as well. noticed couple of my movies having comb effect, had to re-process them by hand... on the other hand i do not know - is autodetection of such things implemented/possible somehow?

thanks in advance! i have created a script which sweeps though couple of vids with all possible combinations of quality (17 to 25) vs presets (veryfast to veryslow). curious to see the difference in results...  all 54 of them :)

**Comment by FallingSnow** [comment]
I do autocropping because for some reason the color in black bars can be different. For example, some videos have black bars that aren't the correct black. When I crop those videos, the black bars created by the player are a more authentic representation of black. Basically I try to leave it up to the video player to decide what black to use. You can disable auto cropping by using the [`--normalize-level` option](https://github.com/FallingSnow/h265ize/issues/56).

I am not as familiar with interlaced videos as I wish. I know detection is possible as it is done in [h265ize-gui](https://github.com/FallingSnow/h265ize-gui). Would you mind sending me a problematic  interlaced video so I can add support for deinterlacing?

I'm interested to see what your results are as well. Good luck.
