### ISSUE TITLE
default destination folder should be the same as the source file

### ISSUE THREAD

**Issue by ssbarnea** [FallingSnow/h265ize#89]
I observed that when run without any parameters `h265ize` would go recursively and convert all files but these files are saved in the current folder instead of the same location (subfolder).

Could it be possible to make the default destination folder as the same as the source file? Note that using  the `-d` parameter does not make any sense because each source file could be in another location.

**Comment by FallingSnow** [comment]
You want files to be saved in the same directory as the source? This cannot be done without deleting the source because the output may have the same name as the source. Try using the `--delete` flag if you're feeling ballsy, it basically accomplishes what you are describing.

On a side note, you should really switch to the git version, it contains more fixes and upgrades.
