### ISSUE TITLE
temporary files should be created in the same location as destination folder

### ISSUE THREAD

**Issue by ssbarnea** [FallingSnow/h265ize#90]
There is an important reason why the default location of the temporary files should be the same as the destination: this could be on a mapped network drive and if temp is on another disk moving the finished file to the destination could take ages, adding unnecessary delays to the whole conversion process. If the locations do match the move is a rename and this is instant.

Also there are some other concerns regarding the size of the system temporary folder, which may not be big enough to store movies.

**Comment by FallingSnow** [comment]
Check to see if your `h265ize --help` lists a `-g` option. That will allow you to set the temp directory. If it doesn't, your version does not use a temp directory.

Also, the destination is not used as the temp folder because often people have programs that watch the destination for new files/changes. If the destination was used as the temp directory, it would constantly trigger a watching program (such as plex) to update the library every time x265 flushed its buffer.
